### ISSUE TITLE
Redirect failed on different port servers on the same host

### ISSUE THREAD

**Issue by lipind** [Onako2/redirect-players#3]
like
serverB 123.123.123.123:1111
serverA 123.123.123.123:2222

use velocity-3.3.0-SNAPSHOT-404 and velocity-3.3.0-SNAPSHOT-400
serverB config
```
host: 123.123.123.123
port: 2222
```
——————————
RROR]: java.io.InterruptedIOException
[01:11:06 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.http2.Http2Stream.waitForIo$okhttp(Http2Stream.kt:662)
[01:11:06 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:140)
[01:11:06 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:96)
[01:11:06 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
[01:11:06 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
[01:11:06 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[01:11:06 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
[01:11:06 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[01:11:06 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:96)
[01:11:06 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[01:11:06 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
[01:11:06 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[01:11:06 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
[01:11:06 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[01:11:06 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
[01:11:06 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.connection.RealCall.execute(RealCall.kt:148)
[01:11:06 ERROR]:       at com.craftmend.openaudiomc.generic.rest.RestRequest.preformRequest(RestRequest.java:180)
[01:11:06 ERROR]:       at com.craftmend.openaudiomc.generic.rest.RestRequest.run(RestRequest.java:91)
[01:11:06 ERROR]:       at com.craftmend.openaudiomc.generic.environment.GlobalConstantService.lambda$scheduleStatusUpdate$0(GlobalConstantService.java:33)
[01:11:06 ERROR]:       at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:285)
[01:11:06 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[01:11:06 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[01:11:06 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[01:11:06 ERROR]:       Suppressed: java.net.SocketTimeoutException: Connect timed out
[01:11:06 ERROR]:               at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
[01:11:06 ERROR]:               at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
[01:11:06 ERROR]:               at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[01:11:06 ERROR]:               at java.base/java.net.Socket.connect(Socket.java:639)
[01:11:06 ERROR]:               at com.craftmend.thirdparty.okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120)
[01:11:06 ERROR]:               at com.craftmend.thirdparty.okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:283)
[01:11:06 ERROR]:               at com.craftmend.thirdparty.okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:195)
[01:11:06 ERROR]:               at com.craftmend.thirdparty.okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:249)
[01:11:06 ERROR]:               at com.craftmend.thirdparty.okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:108)
[01:11:06 ERROR]:               at com.craftmend.thirdparty.okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:76)
[01:11:06 ERROR]:               at com.craftmend.thirdparty.okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:245)
[01:11:06 ERROR]:               at com.craftmend.thirdparty.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
[01:11:06 ERROR]:               ... 16 more

**Comment by Onako2** [comment]
Hi! Thanks for your issue! Currently I can only see that the plugin OpenAudioMc has issues. Could you provide a list of your plugins and a full log with [mclo.gs](mclo.gs)? You can also send it to me via Discord (onako2#0) if you don't want that it is public. Also, when does the issue come up? My current theory is that OpenAudioMc can't handle if the player disconnects because of transfer packetsve. I'll try it tomorrow out. Does your target server have `accepts-transfers` set to true? accepts-transfers must be set to true, forgot to mention that 😆 .

**Comment by lipind** [comment]
> Hi! Thanks for your issue! Currently I can only see that the plugin OpenAudioMc has issues. Could you provide a list of your plugins and a full log with [mclo.gs](mclo.gs)? You can also send it to me via Discord (onako2#0) if you don't want that it is public. Also, when does the issue come up? My current theory is that OpenAudioMc can't handle if the player disconnects because of transfer packetsve. I'll try it tomorrow out. Does your target server have `accepts-transfers` set to true? accepts-transfers must be set to true, forgot to mention that 😆 .

oh， I think it's because `accepts-transfers`. Thank you
I thought it only needed to meet the requirements of player version 1.20.6 and Velocity3.3.0 to use, but I didn't consider that it still requires server1.20.6+

**Comment by Onako2** [comment]
Is the issue solved now?
